import type { Metadata } from "next";
import "./globals.css";
import { ChildrenProps } from "./(pages)/ChildrenProps";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang='ko'>
      <body>
        {children}
      </body>
    </html>
  );
}
